stages:
  - build
  - test
  - deploy


image: moreillon/ci-dind:4bca50d7
services:
  - name: docker:19.03.12-dind

variables:
  APPLICATION_NAME: employee-manager
  ECR_URL: 732469118990.dkr.ecr.ap-northeast-1.amazonaws.com
  CONTAINER_IMAGE: ${ECR_URL}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TEST: ${CONTAINER_IMAGE}:test
  CONTAINER_IMAGE_LATEST: ${CONTAINER_IMAGE}:latest
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_SHORT_SHA}
  K8S_ECR_SECRET: ecr-credentials


build:
  stage: build
  tags:
    - dind
  before_script:
    # Docker hub login
    # Should not be used anymore in the future
    - >
      echo "${DOCKER_HUB_PASSWORD}" |
      docker login
      --username ${DOCKER_HUB_USERNAME}
      --password-stdin
    # ECR login for pushing and pulling
    - >
      aws ecr get-login-password
      | docker login
      --username AWS
      --password-stdin
      ${ECR_URL}
    # Create repository if needed
    - >
      aws ecr create-repository --repository-name ${APPLICATION_NAME}
      || echo "Repository might have already existed"

  script:
    # Build the docker image. Pass proxy variables if set
    - docker build -t ${CONTAINER_IMAGE_TEST} .
    # Pushing image to registry
    - docker push ${CONTAINER_IMAGE_TEST}
    # Cleanup
    - docker image rm ${CONTAINER_IMAGE_TEST}




test:
  stage: test
  tags:
    - dind

  before_script:
    # Docker hub login
    - >
      echo "${DOCKER_HUB_PASSWORD}" |
      docker login
      --username ${DOCKER_HUB_USERNAME}
      --password-stdin
    # ECR login for pushing and pulling
    - >
      aws ecr get-login-password
      | docker login
      --username AWS
      --password-stdin
      ${ECR_URL}
    # Creating network for TDD
    - docker network create tdd
    - >
      docker run
      -d
      --rm
      --name tdd-db
      --network tdd
      --hostname tdd-db
      --env NEO4J_AUTH=none
      neo4j:3.5-community
    - sleep 60 # Wait for Neo4J to become available

  script:
    - >
      docker run
      --rm
      --name tdd-app
      --network tdd
      --env NEO4J_URL=bolt://tdd-db
      --env JWT_SECRET=keyboardcat
      --env TEST_USERNAME=administrator
      --env TEST_PASSWORD=administrator
      ${CONTAINER_IMAGE_TEST}
      npm run coverage
    # If pass, then push the images
    # Tagging
    - docker tag ${CONTAINER_IMAGE_TEST} ${CONTAINER_IMAGE_TAGGED}
    - docker tag ${CONTAINER_IMAGE_TEST} ${CONTAINER_IMAGE_LATEST}
    # Pushing
    - docker push ${CONTAINER_IMAGE_TAGGED}
    - docker push ${CONTAINER_IMAGE_LATEST}
    # Echoing image
    - echo ${CONTAINER_IMAGE_TAGGED}




deploy:
  stage: deploy
  only:
    - master
  before_script:
    - >
      kubectl create secret docker-registry ${K8S_ECR_SECRET}
      --docker-server=${ECR_URL}
      --docker-username=AWS
      --docker-password $(aws ecr get-login-password)
      --dry-run=client -o yaml
      | kubectl apply -f -
  script:
    # create/update the deployment
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
    # Pull latest image by restarting the deployment
    #- kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      # Obtained from GitLab
      namespace: ${KUBERNETES_NAMESPACE}
