stages:
  - build
  - test
  - release
  - deploy

variables:
  APPLICATION_NAME: employee-manager

  ECR_URL: 732469118990.dkr.ecr.ap-northeast-1.amazonaws.com

  CONTAINER_IMAGE: ${ECR_URL}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TEST: ${CONTAINER_IMAGE}:test
  CONTAINER_IMAGE_LATEST: ${CONTAINER_IMAGE}:latest
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_TAG}

  K8S_ECR_SECRET: ecr-credentials

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - >
      aws ecr create-repository --repository-name ${APPLICATION_NAME}
      || echo "Repository might have already existed"

  script:
    - docker build --build-arg APP_VERSION=${CI_COMMIT_TAG} -t ${CONTAINER_IMAGE_TEST} .
    - docker push ${CONTAINER_IMAGE_TEST}

test:
  stage: test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    # Creating network for TDD
    - docker network create tdd
    - >
      docker run
      -d
      --rm
      --name tdd-db
      --network tdd
      --hostname tdd-db
      --env NEO4J_AUTH=none
      --health-cmd "cypher-shell 'RETURN 1'"
      --health-interval 2s
      neo4j:5.12.0
    # Wait until Neo4J is ready (fail after 2 minutes)
    - timeout 120 sh -c 'until [ "$(docker inspect -f {{.State.Health.Status}} tdd-db)" = healthy ]; do sleep 2; done'

  script:
    - >
      docker run
      --rm
      --name tdd-app
      --network tdd
      --env NEO4J_URL=bolt://tdd-db
      --env JWT_SECRET=keyboardcat
      --env TEST_USERNAME=administrator
      --env TEST_PASSWORD=administrator
      ${CONTAINER_IMAGE_TEST}
      npm run coverage

release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - docker pull ${CONTAINER_IMAGE_TEST}
    # Tagging
    - docker tag ${CONTAINER_IMAGE_TEST} ${CONTAINER_IMAGE_TAGGED}
    - docker tag ${CONTAINER_IMAGE_TEST} ${CONTAINER_IMAGE_LATEST}
    # Pushing
    - docker push ${CONTAINER_IMAGE_TAGGED}
    - docker push ${CONTAINER_IMAGE_LATEST}

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - kubectl config use-context eks/gitlab-agent-for-kubernetes:eks
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
