import swaggerAutogen from "swagger-autogen"
import { name } from "./package.json"
import { APP_VERSION } from "./config"

const generate = swaggerAutogen()

const doc = {
  info: {
    version: APP_VERSION,
    title: name,
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  basePath: "/",
  consumes: ["application/json"],
  produces: ["application/json"],
}

const outputFile = "./swagger-output.json"
const endpointsFiles = ["./index.ts"]

generate(outputFile, endpointsFiles, doc)
